#!/usr/bin/env bash

set -e

if [ ! -d ./test/_plugins ]; then
  mkdir ./test/_plugins
fi
cp ./lib/jekyll-auto-image-include.rb ./test/_plugins/

cd test
bundle exec jekyll build
bundle exec htmlproofer ./_site/
cd ..

rm -rf ./test/_plugins
